name: Sanitize Dependabot Gradle Wrapper PR
description: "Sanitizes and removes binary file changes when the gradle wrapper is updated."

inputs:
  access_token:
    description: "GitHub access token with contents:write permission"
    required: true

  committer_name:
    description: "Optional committer name (defaults to PAT owner)"
    required: false
    default: ""

  committer_email:
    description: "Optional committer email (defaults to PAT owner @users.noreply.github.com"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout PR branch
      if: >
        github.event.pull_request.user.login == 'dependabot[bot]' &&
        startsWith(github.event.pull_request.title, 'Bump gradle-wrapper') &&
        github.event.pull_request.head.user.name == 'dependabot[bot]'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ inputs.access_token }}
        persist-credentials: false

    - name: Rewrite latest commit to only include gradle-wrapper.properties
      if: >
        github.event.pull_request.user.login == 'dependabot[bot]' &&
        startsWith(github.event.pull_request.title, 'Bump gradle-wrapper') &&
        github.event.pull_request.head.user.name == 'dependabot[bot]'
      shell: bash
      run: |
        set -euo pipefail
        echo "Resolving committer identity"
        
        if [ -z "${{ inputs.committer_name }}" ] || [ -z "${{ inputs.committer_email }}" ]; then
          echo "Querying GitHub API for token owner"
        
          GH_USER_JSON="$(curl -sSf \
            -H "Authorization: Bearer ${{ inputs.access_token }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/user)"
        
          GH_LOGIN="$(echo "$GH_USER_JSON" | jq -r .login)"
        
          if [ "$GH_LOGIN" = "null" ] || [ -z "$GH_LOGIN" ]; then
            echo "Failed to determine token owner"
            exit 1
          fi
        fi
        
        COMMITTER_NAME="${{ inputs.committer_name }}"
        COMMITTER_EMAIL="${{ inputs.committer_email }}"
        
        if [ -z "$COMMITTER_NAME" ]; then
          COMMITTER_NAME="$GH_LOGIN"
        fi
        
        if [ -z "$COMMITTER_EMAIL" ]; then
          COMMITTER_EMAIL="$GH_LOGIN@users.noreply.github.com"
        fi
        
        echo "Using committer:"
        echo "  Name:  $COMMITTER_NAME"
        echo "  Email: $COMMITTER_EMAIL"

        echo "Targeting latest commit (HEAD)"
        TARGET_COMMIT="HEAD"

        echo "Capturing original author and commit message"
        OLD_AUTHOR="$(git show -s --format='%an <%ae>' "$TARGET_COMMIT")"
        OLD_MSG="$(git show -s --format=%B "$TARGET_COMMIT")"

        echo "Appending sanitizer tag to commit message"
        NEW_MSG="$OLD_MSG (Sanitized by $COMMITTER_NAME)"

        echo "Checking out HEAD"
        git checkout "$TARGET_COMMIT"

        echo "Amending commit to empty it"
        git -c user.name="$COMMITTER_NAME" \
            -c user.email="$COMMITTER_EMAIL" \
            commit --amend --no-edit --allow-empty

        echo "Removing all files from index"
        git reset HEAD^

        echo "Staging all gradle-wrapper.properties files"
        git add ':(glob)**/gradle-wrapper.properties'

        if [ -z "$(git diff --cached --name-only)" ]; then
          echo "No gradle-wrapper.properties files found to stage. Aborting."
          exit 1
        fi

        echo "Creating new commit with preserved author and overridden committer"
        git -c user.name="$COMMITTER_NAME" \
            -c user.email="$COMMITTER_EMAIL" \
            commit --author="$OLD_AUTHOR" -m "$NEW_MSG"

        echo "Pushing rewritten history to PR branch"
        git -c user.name="$COMMITTER_NAME" \
            -c user.email="$COMMITTER_EMAIL" \
            -c http.https://github.com/.extraheader="AUTHORIZATION: basic $(printf 'x-access-token:%s' "${{ inputs.access_token }}" | base64 -w0)" \
            push --force origin HEAD:"$GITHUB_HEAD_REF"


        echo "Sanitize workflow completed successfully"
