name: Sanitize Dependabot Gradle Wrapper PR
description: "Sanitizes and removes binary file changes when the gradle wrapper is updated."

inputs:
  committer_name:
    description: "Optional committer name"
    required: false
    default: "Wilderforge Sanitizer"
  committer_email:
    description: "Optional committer email"
    required: false
    default: "<>"

runs:
  using: "composite"
  steps:
    - name: Checkout PR branch
      if: >
        github.event.pull_request.user.login == 'dependabot[bot]' &&
        startsWith(github.event.pull_request.title, 'Bump gradle-wrapper')
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true

    - name: Rewrite latest commit to only include gradle-wrapper.properties
      if: >
        github.event.pull_request.user.login == 'dependabot[bot]' &&
        startsWith(github.event.pull_request.title, 'Bump gradle-wrapper')
      shell: bash
      run: |
        set -euo pipefail

        echo "Using inputs or defaults for committer"
        COMMITTER_NAME="${{ inputs.committer_name }}"
        COMMITTER_EMAIL="${{ inputs.committer_email }}"

        echo "Targeting latest commit (HEAD)"
        TARGET_COMMIT="HEAD"

        echo "Capturing original author and commit message"
        OLD_AUTHOR="$(git show -s --format='%an <%ae>' "$TARGET_COMMIT")"
        OLD_MSG="$(git show -s --format=%B "$TARGET_COMMIT")"

        echo "Appending sanitizer tag to commit message"
        NEW_MSG="$OLD_MSG (Sanitized by $COMMITTER_NAME)"

        echo "Checking out HEAD"
        git checkout "$TARGET_COMMIT"

        echo "Amending commit to empty it"
        git -c user.name="$COMMITTER_NAME" \
            -c user.email="$COMMITTER_EMAIL" \
            commit --amend --no-edit --allow-empty

        echo "Removing all files from index"
        git reset HEAD^

        echo "Staging all gradle-wrapper.properties files"
        git add ':(glob)**/gradle-wrapper.properties'

        if [ -z "$(git diff --cached --name-only)" ]; then
          echo "No gradle-wrapper.properties files found to stage. Aborting."
          exit 1
        fi

        echo "Creating new commit with preserved author and overridden committer"
        git -c user.name="$COMMITTER_NAME" \
            -c user.email="$COMMITTER_EMAIL" \
            commit --author="$OLD_AUTHOR" -m "$NEW_MSG"

        echo "Pushing rewritten history to PR branch"
        git -c user.name="$COMMITTER_NAME" \
            -c user.email="$COMMITTER_EMAIL" \
            push --force-with-lease origin HEAD:"$GITHUB_HEAD_REF"


        echo "Sanitize workflow completed successfully"
